security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker

      form_login:
        login_path: app_login
        check_path: app_login
        success_handler: App\Security\LoginSuccessHandler

      logout:
        path: app_logout
        target: app_login

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/connect/google, roles: PUBLIC_ACCESS }
    - { path: ^/connect/facebook, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/auth/faceid, roles: PUBLIC_ACCESS }
    - { path: ^/auth/facepp, roles: PUBLIC_ACCESS }
    - { path: ^/health/facepp, roles: PUBLIC_ACCESS }
    - { path: ^/api/devise/taux, roles: PUBLIC_ACCESS }
    - { path: ^/api/devise, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/salary, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/reclamations, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/admin/reclamations, roles: ROLE_ADMIN }

    # Admin area
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/transaction, roles: ROLE_ADMIN }
    - { path: ^/user, roles: ROLE_ADMIN }

    # Role-based sections
    - { path: ^/salary, roles: ROLE_SALARY }
    - { path: ^/student, roles: ROLE_ETUDIANT }
    - { path: ^/certification, roles: ROLE_ETUDIANT }
